"""empty message

Revision ID: 760b9b7b3d51
Revises: d2abf977065f
Create Date: 2022-10-03 15:09:28.254356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760b9b7b3d51'
down_revision = 'd2abf977065f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('friend', sa.String(length=20), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friend_request')
    # ### end Alembic commands ###
